NPTEL_CHUNK_SUMMARY_V1 = "NPTEL_CHUNK_SUMMARY_V1"
NPTEL_LECTURE_MERGE_V1 = "NPTEL_LECTURE_MERGE_V1"
NPTEL_LECTURE_NOTES_V1 = "NPTEL_LECTURE_NOTES_V1"
NPTEL_WEEK_SYNTHESIS_V1 = "NPTEL_WEEK_SYNTHESIS_V1"
NPTEL_COURSE_SYNTHESIS_V1 = "NPTEL_COURSE_SYNTHESIS_V1"

LECTURE_PROMPT_VERSION = NPTEL_LECTURE_NOTES_V1
CHUNK_PROMPT_VERSION = NPTEL_CHUNK_SUMMARY_V1
WEEK_PROMPT_VERSION = NPTEL_WEEK_SYNTHESIS_V1
COURSE_PROMPT_VERSION = NPTEL_COURSE_SYNTHESIS_V1
